"""Constants for strategy-backtester engine."""

BROKER_KITE = "kite"
BROKER_ZERODHA = "zerodha"

BROKER_ZERO_COMMISSION = "zero_commission"

EXCHANGE_BROKER_MAP = {
    "NSE": BROKER_KITE,
    "BSE": BROKER_KITE,
    "NFO": BROKER_KITE,
    "BFO": BROKER_KITE,
    "MCX": BROKER_KITE,
    "CDS": BROKER_KITE,
    "NASDAQ": BROKER_ZERO_COMMISSION,
    "NYSE": BROKER_ZERO_COMMISSION,
    "AMEX": BROKER_ZERO_COMMISSION,
}

SECONDS_IN_ONE_DAY = 86400
SECONDS_IN_ONE_HOUR = 3600
SECONDS_IN_ONE_MINUTE = 60
SECONDS_IN_ONE_YEAR = 365 * SECONDS_IN_ONE_DAY
