static:
  strategy_type: extended_ibs
  start_margin: 500000
  start_epoch: 1167609600      # 2007-01-01
  end_epoch: 1741219200        # 2025-03-06
  prefetch_days: 400
  data_granularity: day

scanner:
  instruments:
    - [{exchange: US, symbols: []}]
  price_threshold: [20]
  avg_day_transaction_threshold:
    - {period: 20, threshold: 50000000}
  n_day_gain_threshold:
    - {n: 360, threshold: -999}

entry:
  ibs_threshold: [0.3]
  sma_trend_period: [0, 200]

exit:
  max_hold_days: [15, 30]

simulation:
  default_sorting_type: [top_gainer]
  order_sorting_type: [top_gainer]
  order_ranking_window_days: [30]
  max_positions: [5, 10, 20]
  max_positions_per_instrument: [1]
  order_value_multiplier: [1]
  max_order_value:
    - {type: fixed, value: 50000}
