static:
  strategy_type: eod_technical
  start_margin: 9999999
  start_epoch: 1422748800
  end_epoch: 1738368000
  prefetch_days: 400
  data_granularity: day

scanner:
  instruments:
    - [{exchange: NSE, symbols: []}]
  price_threshold: [45]
  avg_day_transaction_threshold:
    - {period: 125, threshold: 20000000}
    - {period: 125, threshold: 50000000}
    - {period: 125, threshold: 70000000}
    - {period: 125, threshold: 150000000}
    - {period: 125, threshold: 370000000}
  n_day_gain_threshold:
    - {n: 360, threshold: 0}

entry:
  n_day_ma: [3]
  n_day_high: [2]
  direction_score:
    - {n_day_ma: 3, score: 0.54}

exit:
  min_hold_time_days: [10]
  trailing_stop_loss: [15]

simulation:
  default_sorting_type: [top_gainer]
  order_sorting_type: [top_performer]
  order_ranking_window_days: [180]
  max_positions: [10]
  max_positions_per_instrument: [1]
  order_value_multiplier: [1]
  max_order_value:
    - {type: percentage_of_instrument_avg_txn, value: 4.5}
