static:
  strategy_type: index_green_candle
  start_margin: 10000000       # 1 Crore
  start_epoch: 1262304000      # 2010-01-01
  end_epoch: 1741219200        # 2025-03-06
  prefetch_days: 30
  data_granularity: day

scanner:
  instruments:
    - [{exchange: NSE, symbols: [NIFTYBEES]}]
  price_threshold: [1]
  avg_day_transaction_threshold:
    - {period: 20, threshold: 1000000}
  n_day_gain_threshold:
    - {n: 30, threshold: -999}

entry:
  green_candles: [2]

exit:
  red_candles_exit: [1]
  take_profit_pct: [0]
  stop_loss_pct: [0]

simulation:
  default_sorting_type: [top_gainer]
  order_sorting_type: [top_gainer]
  order_ranking_window_days: [30]
  max_positions: [1]
  max_positions_per_instrument: [1]
  order_value_multiplier: [0.95]
  max_order_value:
    - {type: fixed, value: 100000000}
